### PR TITLE
Adding ability to reindex existing code base

### PR DESCRIPTION
**Pull request by nsrinath**
Previously the script could handle only three operations - setup, start and stop grokit server

I felt the need to reindex an existing project and hence made the required changes. Sending a PR your way in case you think this might be a good feature for your project.

### CODE REVIEW

**Comment by nsrinath** [comment]
Hey Raghu,

Reindexing will work only if the project was indexed the first time (using the action=setup switch).
There is a new action for reindex (action=reindex). Not sure what you mean by the same command in your comment - Is that the final java command that you're referring to?

I will look into the link that you provided. Until about few weeks ago, I did not see any issues with reindexing and -W but I've begun to see a few issues now. I will see if not specifying the -W option fixes those issues.

About reducing the lines of code in the diff, I renamed the indexing function from create_og_index to index_og since calling 'create_og_index' for reindexing (index is already created when we re-index a  project) seemed a bit un-intuitive. The index_og function indexes the given source code.
 
-Srinath

**Comment by sandeep-mvd** [comment]
Hi, Why is this not pulled into source code? Is it not working?

**Comment by sandeep-mvd** [comment]
Hi Raghu, please consider taking this pull request. It is very useful to re-index. Without this feature, it is very inconvenient as the already inndexed tables are no more valid after a git pull.

**Comment by sandeepmvd** [comment]
@raghusesha Thank you.
Would you also consider updating the binaries that include this patch. Binaries are really easy to use and are helpful.

**Comment by raghusesha** [comment]
Actually, I don't have the setup that I used to create binaries anymore..
Do you have that setup?

**Comment by sandeepmvd** [comment]
No. I tried to make one, but was not successful. So, I am using the binaries instead.
@nsrinath May be you have it with you?

**Comment by nsrinath** [comment]
No @sandeep-mvd . I never used the binary form - I execute the script directly.

**Comment by sandeepmvd** [comment]
@nsrinath 
I am trying to setup the environment.
As per the instructions, downloaded the needed packages and placed them under tools.

Here is the op of tree command
```
sandeep@mypc ~/sw/grokit/grokit/src $ tree
.
├── grokit.py
├── platdefines.py
├── platdefines.pyc
├── tools
│   ├── apache-tomcat-8.5.12.tar.gz
│   ├── ctags-5.8.tar.gz
│   ├── jdk-8u121-linux-x64.tar.gz
│   └── opengrok-0.13-rc10.tar.gz
├── utils.py
└── utils.pyc
```
But when i am trying to use the script it fails without mentioning any reasons
```
sandeep@officepc ~/sw/grokit/grokit/src $ python grokit.py --ppath=/home/sandeep/source/test_code --action=setup
Setting up index...



Setup failed to complete!
```

Could you post the op of tree command from src directory? I think i am either missing something or the versions i am using are incorrect. Thank you.

**Comment by raghusesha** [comment]
Can you try using the pre-built binaries available at github?

**Comment by sandeepmvd** [comment]
@raghusesha The binaries are fine but they donot have the reindex support. Hence I am trying to setup the environment and use the scripts.

**Comment by nsrinath** [comment]
While my python files are just the same as yours, the tools directory is different

- apache-tomcat-8.0.8.tar.gz
- exuberant-ctags.tar
- jre-7u65-linux-x64.tar.gz
- opengrok-0.12.1.tar.gz
- README.txt

**Comment by sandeepmvd** [comment]
Thanks @nsrinath 
I took all of them from binary folder and replaced into tools/ directory. It works for me now.
Also, I confirmed reindexing is workng. Thank you.

**Comment by nsrinath** [comment]
Great. Good to know!

**Pull request merged**
